name: dotenv-cpp-prebuilt-release-actions-workflow
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'c*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    name: Create Release
    runs-on: windows-latest
    env:
      mingwTargetZip: dotenv-cpp-${{ github.ref_name }}-mingw.zip
    steps:
      - name: git clone dotenv-cpp
        run: git clone https://github.com/laserpants/dotenv-cpp.git # master

      - name: cmake dotenv-cpp
        shell: cmd
        run: cd dotenv-cpp && cmake.exe -G"MinGW Makefiles" -DBUILD_SHARED_LIBS=OFF -DCMAKE_INSTALL_PREFIX="build/dotenv-cpp" -B./build
      
      - name: mingw build 
        shell: cmd
        run: cd dotenv-cpp\build && mingw32-make install
        
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: "zip"
          directory: "dotenv-cpp/build/dotenv-cpp"
          filename: "${{ env.mingwTargetZip }}"
          
      - name: Release prebuilt
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dotenv-cpp/build/dotenv-cpp/${{ env.mingwTargetZip }}"
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
